version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.4.0-alpine3.20
    ports:
      - 6379:6379
